require 'debug'
require'digest'
require 'require_all'
require_relative 'lib/smart_enumerators.rb'
require_relative 'lib/base_strategy.rb'
require_relative 'lib/house.rb'
require_all 'lib/strategies'
require_all 'lib'
