require 'debug'
require 'json'
require 'require_all'
require 'sinatra'
require'digest'
require_relative 'lib/house.rb'
require_relative 'lib/base_strategy.rb'
require_all 'lib/strategies'

require_all 'lib'
